package main

import "encoding/xml"

// Generated by https://www.onlinetool.io/xmltogo/
// Based on IO-Device-Desc-Guideline_10022_V113_Apr21/Examples/IO-Link-01-BasicDevice-20210415-IODD1.1.xml

type IODevice struct {
	XMLName        xml.Name `xml:"IODevice"`
	Text           string   `xml:",chardata"`
	Xmlns          string   `xml:"xmlns,attr"`
	Xsi            string   `xml:"xsi,attr"`
	SchemaLocation string   `xml:"schemaLocation,attr"`
	DocumentInfo   struct {
		Text        string `xml:",chardata"`
		Version     string `xml:"version,attr"`
		ReleaseDate string `xml:"releaseDate,attr"`
		Copyright   string `xml:"copyright,attr"`
	} `xml:"DocumentInfo"`
	ProfileHeader struct {
		Text                  string `xml:",chardata"`
		ProfileIdentification string `xml:"ProfileIdentification"`
		ProfileRevision       string `xml:"ProfileRevision"`
		ProfileName           string `xml:"ProfileName"`
		ProfileSource         string `xml:"ProfileSource"`
		ProfileClassID        string `xml:"ProfileClassID"`
		ISO15745Reference     struct {
			Text              string `xml:",chardata"`
			ISO15745Part      string `xml:"ISO15745Part"`
			ISO15745Edition   string `xml:"ISO15745Edition"`
			ProfileTechnology string `xml:"ProfileTechnology"`
		} `xml:"ISO15745Reference"`
	} `xml:"ProfileHeader"`
	ProfileBody struct {
		Text           string `xml:",chardata"`
		DeviceIdentity struct {
			Text       string `xml:",chardata"`
			VendorId   string `xml:"vendorId,attr"`
			DeviceId   string `xml:"deviceId,attr"`
			VendorName string `xml:"vendorName,attr"`
			VendorText struct {
				Text   string `xml:",chardata"`
				TextId string `xml:"textId,attr"`
			} `xml:"VendorText"`
			VendorUrl struct {
				Text   string `xml:",chardata"`
				TextId string `xml:"textId,attr"`
			} `xml:"VendorUrl"`
			VendorLogo struct {
				Text string `xml:",chardata"`
				Name string `xml:"name,attr"`
			} `xml:"VendorLogo"`
			DeviceName struct {
				Text   string `xml:",chardata"`
				TextId string `xml:"textId,attr"`
			} `xml:"DeviceName"`
			DeviceFamily struct {
				Text   string `xml:",chardata"`
				TextId string `xml:"textId,attr"`
			} `xml:"DeviceFamily"`
			DeviceVariantCollection struct {
				Text          string `xml:",chardata"`
				DeviceVariant struct {
					Text         string `xml:",chardata"`
					ProductId    string `xml:"productId,attr"`
					DeviceSymbol string `xml:"deviceSymbol,attr"`
					DeviceIcon   string `xml:"deviceIcon,attr"`
					Name         struct {
						Text   string `xml:",chardata"`
						TextId string `xml:"textId,attr"`
					} `xml:"Name"`
					Description struct {
						Text   string `xml:",chardata"`
						TextId string `xml:"textId,attr"`
					} `xml:"Description"`
				} `xml:"DeviceVariant"`
			} `xml:"DeviceVariantCollection"`
		} `xml:"DeviceIdentity"`
		DeviceFunction struct {
			Text     string `xml:",chardata"`
			Features struct {
				Text                  string `xml:",chardata"`
				BlockParameter        string `xml:"blockParameter,attr"`
				DataStorage           string `xml:"dataStorage,attr"`
				ProfileCharacteristic string `xml:"profileCharacteristic,attr"`
				SupportedAccessLocks  struct {
					Text                  string `xml:",chardata"`
					Parameter             string `xml:"parameter,attr"`
					DataStorage           string `xml:"dataStorage,attr"`
					LocalParameterization string `xml:"localParameterization,attr"`
					LocalUserInterface    string `xml:"localUserInterface,attr"`
				} `xml:"SupportedAccessLocks"`
			} `xml:"Features"`
			VariableCollection struct {
				Text           string `xml:",chardata"`
				StdVariableRef []struct {
					Text                    string `xml:",chardata"`
					ID                      string `xml:"id,attr"`
					DefaultValue            string `xml:"defaultValue,attr"`
					ExcludedFromDataStorage string `xml:"excludedFromDataStorage,attr"`
					FixedLengthRestriction  string `xml:"fixedLengthRestriction,attr"`
					StdSingleValueRef       []struct {
						Text  string `xml:",chardata"`
						Value string `xml:"value,attr"`
					} `xml:"StdSingleValueRef"`
				} `xml:"StdVariableRef"`
				Variable []struct {
					Text                    string `xml:",chardata"`
					ID                      string `xml:"id,attr"`
					Index                   string `xml:"index,attr"`
					AccessRights            string `xml:"accessRights,attr"`
					DefaultValue            string `xml:"defaultValue,attr"`
					ExcludedFromDataStorage string `xml:"excludedFromDataStorage,attr"`
					Datatype                struct {
						Text        string `xml:",chardata"`
						Type        string `xml:"type,attr"`
						FixedLength string `xml:"fixedLength,attr"`
						Encoding    string `xml:"encoding,attr"`
						BitLength   string `xml:"bitLength,attr"`
					} `xml:"Datatype"`
					Name struct {
						Text   string `xml:",chardata"`
						TextId string `xml:"textId,attr"`
					} `xml:"Name"`
					Description struct {
						Text   string `xml:",chardata"`
						TextId string `xml:"textId,attr"`
					} `xml:"Description"`
				} `xml:"Variable"`
			} `xml:"VariableCollection"`
			ProcessDataCollection struct {
				Text        string `xml:",chardata"`
				ProcessData struct {
					Text          string `xml:",chardata"`
					ID            string `xml:"id,attr"`
					ProcessDataIn struct {
						Text      string `xml:",chardata"`
						ID        string `xml:"id,attr"`
						BitLength string `xml:"bitLength,attr"`
						Datatype  struct {
							Text      string `xml:",chardata"`
							Type      string `xml:"type,attr"`
							BitLength string `xml:"bitLength,attr"`
						} `xml:"Datatype"`
						Name struct {
							Text   string `xml:",chardata"`
							TextId string `xml:"textId,attr"`
						} `xml:"Name"`
					} `xml:"ProcessDataIn"`
					ProcessDataOut struct {
						Text      string `xml:",chardata"`
						ID        string `xml:"id,attr"`
						BitLength string `xml:"bitLength,attr"`
						Datatype  struct {
							Text      string `xml:",chardata"`
							Type      string `xml:"type,attr"`
							BitLength string `xml:"bitLength,attr"`
						} `xml:"Datatype"`
						Name struct {
							Text   string `xml:",chardata"`
							TextId string `xml:"textId,attr"`
						} `xml:"Name"`
					} `xml:"ProcessDataOut"`
				} `xml:"ProcessData"`
			} `xml:"ProcessDataCollection"`
			ErrorTypeCollection struct {
				Text            string `xml:",chardata"`
				StdErrorTypeRef []struct {
					Text           string `xml:",chardata"`
					Code           string `xml:"code,attr"`
					AdditionalCode string `xml:"additionalCode,attr"`
				} `xml:"StdErrorTypeRef"`
			} `xml:"ErrorTypeCollection"`
			EventCollection struct {
				Text        string `xml:",chardata"`
				StdEventRef struct {
					Text string `xml:",chardata"`
					Code string `xml:"code,attr"`
				} `xml:"StdEventRef"`
			} `xml:"EventCollection"`
			UserInterface struct {
				Text           string `xml:",chardata"`
				MenuCollection struct {
					Text string `xml:",chardata"`
					Menu []struct {
						Text        string `xml:",chardata"`
						ID          string `xml:"id,attr"`
						VariableRef []struct {
							Text                   string `xml:",chardata"`
							VariableId             string `xml:"variableId,attr"`
							AccessRightRestriction string `xml:"accessRightRestriction,attr"`
							Button                 struct {
								Text        string `xml:",chardata"`
								ButtonValue string `xml:"buttonValue,attr"`
								Description struct {
									Text   string `xml:",chardata"`
									TextId string `xml:"textId,attr"`
								} `xml:"Description"`
							} `xml:"Button"`
						} `xml:"VariableRef"`
						MenuRef []struct {
							Text   string `xml:",chardata"`
							MenuId string `xml:"menuId,attr"`
						} `xml:"MenuRef"`
						Name struct {
							Text   string `xml:",chardata"`
							TextId string `xml:"textId,attr"`
						} `xml:"Name"`
					} `xml:"Menu"`
				} `xml:"MenuCollection"`
				ObserverRoleMenuSet struct {
					Text               string `xml:",chardata"`
					IdentificationMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"IdentificationMenu"`
					ParameterMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"ParameterMenu"`
					ObservationMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"ObservationMenu"`
					DiagnosisMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"DiagnosisMenu"`
				} `xml:"ObserverRoleMenuSet"`
				MaintenanceRoleMenuSet struct {
					Text               string `xml:",chardata"`
					IdentificationMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"IdentificationMenu"`
					ParameterMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"ParameterMenu"`
					ObservationMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"ObservationMenu"`
					DiagnosisMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"DiagnosisMenu"`
				} `xml:"MaintenanceRoleMenuSet"`
				SpecialistRoleMenuSet struct {
					Text               string `xml:",chardata"`
					IdentificationMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"IdentificationMenu"`
					ParameterMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"ParameterMenu"`
					ObservationMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"ObservationMenu"`
					DiagnosisMenu struct {
						Text   string `xml:",chardata"`
						MenuId string `xml:"menuId,attr"`
					} `xml:"DiagnosisMenu"`
				} `xml:"SpecialistRoleMenuSet"`
			} `xml:"UserInterface"`
		} `xml:"DeviceFunction"`
	} `xml:"ProfileBody"`
	CommNetworkProfile struct {
		Text            string `xml:",chardata"`
		Type            string `xml:"type,attr"`
		IolinkRevision  string `xml:"iolinkRevision,attr"`
		TransportLayers struct {
			Text          string `xml:",chardata"`
			PhysicalLayer struct {
				Text                string `xml:",chardata"`
				Bitrate             string `xml:"bitrate,attr"`
				MinCycleTime        string `xml:"minCycleTime,attr"`
				SioSupported        string `xml:"sioSupported,attr"`
				MSequenceCapability string `xml:"mSequenceCapability,attr"`
				Connection          struct {
					Text       string `xml:",chardata"`
					Type       string `xml:"type,attr"`
					ProductRef struct {
						Text      string `xml:",chardata"`
						ProductId string `xml:"productId,attr"`
					} `xml:"ProductRef"`
					Wire1 struct {
						Text     string `xml:",chardata"`
						Function string `xml:"function,attr"`
					} `xml:"Wire1"`
					Wire2 struct {
						Text     string `xml:",chardata"`
						Function string `xml:"function,attr"`
					} `xml:"Wire2"`
					Wire3 struct {
						Text     string `xml:",chardata"`
						Function string `xml:"function,attr"`
					} `xml:"Wire3"`
					Wire4 struct {
						Text     string `xml:",chardata"`
						Function string `xml:"function,attr"`
					} `xml:"Wire4"`
				} `xml:"Connection"`
			} `xml:"PhysicalLayer"`
		} `xml:"TransportLayers"`
		Test struct {
			Text    string `xml:",chardata"`
			Config1 struct {
				Text      string `xml:",chardata"`
				Index     string `xml:"index,attr"`
				TestValue string `xml:"testValue,attr"`
			} `xml:"Config1"`
			Config2 struct {
				Text      string `xml:",chardata"`
				Index     string `xml:"index,attr"`
				TestValue string `xml:"testValue,attr"`
			} `xml:"Config2"`
			Config3 struct {
				Text      string `xml:",chardata"`
				Index     string `xml:"index,attr"`
				TestValue string `xml:"testValue,attr"`
			} `xml:"Config3"`
			Config7 struct {
				Text         string `xml:",chardata"`
				Index        string `xml:"index,attr"`
				EventTrigger []struct {
					Text           string `xml:",chardata"`
					AppearValue    string `xml:"appearValue,attr"`
					DisappearValue string `xml:"disappearValue,attr"`
				} `xml:"EventTrigger"`
			} `xml:"Config7"`
		} `xml:"Test"`
	} `xml:"CommNetworkProfile"`
	ExternalTextCollection struct {
		Text            string `xml:",chardata"`
		PrimaryLanguage struct {
			Chardata string `xml:",chardata"`
			Lang     string `xml:"lang,attr"`
			Text     []struct {
				Text  string `xml:",chardata"`
				ID    string `xml:"id,attr"`
				Value string `xml:"value,attr"`
			} `xml:"Text"`
		} `xml:"PrimaryLanguage"`
	} `xml:"ExternalTextCollection"`
	Stamp struct {
		Text    string `xml:",chardata"`
		Crc     string `xml:"crc,attr"`
		Checker struct {
			Text    string `xml:",chardata"`
			Name    string `xml:"name,attr"`
			Version string `xml:"version,attr"`
		} `xml:"Checker"`
	} `xml:"Stamp"`
}
